### ISSUE TITLE
grammar bug: a INNER JOIN b has incorrect join_type

### ISSUE THREAD

**Issue by machow** [datacamp/antlr-plsql#27]
From the `table_ref` rule, antlr thinks that INNER is the table alias (e.g. `a INNER`). I think the simplest way to fix this is to add a new matching rule to table_ref that matches a non-aliased table followed by a join.

https://github.com/datacamp/antlr-plsql/blob/master/antlr_plsql/plsql.g4#L955

**Comment by filipsch** [comment]
This is an issue in the 'joining data in postgresql course', when non-aliased inner joins are checked. In the past, this failed silently: when the student_ast ended up being none, has_equal_ast would just do `repr(None) == repr(None)`, which passes. Because of [this change](https://github.com/datacamp/protowhat/commit/70303ea8d5b9303bb1b380bd95629d1e46cd6981), however, there is now an explicit fail (and it should be there).
I will disable some tests in the postgresql course until this is fixed, because they are currently not doing anything meaningful anyways.
cc @ismayc
